spring:
  redis:
    host: 192.168.195.111
    port: 6379
zuul:
  #所有服务可以传递cookie
  sensitive-headers: 
  routes:
    myProduct:
      path: /myProduct/**
      serviceId: product
      sensitiveHeaders:
    # 简洁写法
#    product: /myProduct/**
#    myConfig:
#      path: /myConfig/**
#      serviceId: config
    config: /myConfig/**
  # 排除某些路由
  ignored-patterns: adfadf
    - /**/product/listForOrder
